name: Update readme.io documentation
on:
  push:
    branches:
      - master
jobs:
  update-documentation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Update readme.io documentation
        uses: apivideo/api.video-readmeio-document-sync-action@1.2
        with:
          document-slug: apivideo-android-kotlin-livestream-module
          markdown-file-path: README.md
          readme-io-api-key: ${{ secrets.README_IO_API_KEY }}
          make-relative-links-absolute: true
  update-api-documentation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 12
        uses: actions/setup-java@v1
        with:
          java-version: 12
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Generate API documentation
        run: ./gradlew dokkaHtml
      - name: Deploy API documentation to Github Pages
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: livestream/build/dokka/html